window.esdocSearchIndex = [
  [
    "health-state-registry/src/adapters/adapter.js~adapter",
    "class/src/adapters/Adapter.js~Adapter.html",
    "<span>Adapter</span> <span class=\"search-result-import-path\">health-state-registry/src/adapters/Adapter.js</span>",
    "class"
  ],
  [
    "health-state-registry/src/errors/customerror.js~customerror",
    "class/src/errors/CustomError.js~CustomError.html",
    "<span>CustomError</span> <span class=\"search-result-import-path\">health-state-registry/src/errors/CustomError.js</span>",
    "class"
  ],
  [
    "health-state-registry/src/errors/notfounderror.js~notfounderror",
    "class/src/errors/NotFoundError.js~NotFoundError.html",
    "<span>NotFoundError</span> <span class=\"search-result-import-path\">health-state-registry/src/errors/NotFoundError.js</span>",
    "class"
  ],
  [
    "health-state-registry/src/errors/notimplementederror.js~notimplementederror",
    "class/src/errors/NotImplementedError.js~NotImplementedError.html",
    "<span>NotImplementedError</span> <span class=\"search-result-import-path\">health-state-registry/src/errors/NotImplementedError.js</span>",
    "class"
  ],
  [
    "health-state-registry~registry",
    "class/src/Registry.js~Registry.html",
    "<span>Registry</span> <span class=\"search-result-import-path\">health-state-registry</span>",
    "class"
  ],
  [
    "health-state-registry/src/adapters/volatileadapter.js~volatileadapter",
    "class/src/adapters/VolatileAdapter.js~VolatileAdapter.html",
    "<span>VolatileAdapter</span> <span class=\"search-result-import-path\">health-state-registry/src/adapters/VolatileAdapter.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/registry.js",
    "file/src/Registry.js.html",
    "src/Registry.js",
    "file"
  ],
  [
    "src/registry.js~identifier",
    "typedef/index.html#static-typedef-Identifier",
    "src/Registry.js~Identifier",
    "typedef"
  ],
  [
    "src/registry.js~registry#adapter",
    "class/src/Registry.js~Registry.html#instance-member-adapter",
    "src/Registry.js~Registry#adapter",
    "member"
  ],
  [
    "src/registry.js~registry#constructor",
    "class/src/Registry.js~Registry.html#instance-constructor-constructor",
    "src/Registry.js~Registry#constructor",
    "method"
  ],
  [
    "src/registry.js~registry#createsystem",
    "class/src/Registry.js~Registry.html#instance-method-createSystem",
    "src/Registry.js~Registry#createSystem",
    "method"
  ],
  [
    "src/registry.js~registry#deletesystem",
    "class/src/Registry.js~Registry.html#instance-method-deleteSystem",
    "src/Registry.js~Registry#deleteSystem",
    "method"
  ],
  [
    "src/registry.js~registry#getsystem",
    "class/src/Registry.js~Registry.html#instance-method-getSystem",
    "src/Registry.js~Registry#getSystem",
    "method"
  ],
  [
    "src/registry.js~registry#updatesystem",
    "class/src/Registry.js~Registry.html#instance-method-updateSystem",
    "src/Registry.js~Registry#updateSystem",
    "method"
  ],
  [
    "src/adapters/adapter.js",
    "file/src/adapters/Adapter.js.html",
    "src/adapters/Adapter.js",
    "file"
  ],
  [
    "src/adapters/adapter.js~adapter#assignsystemid",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-assignSystemId",
    "src/adapters/Adapter.js~Adapter#assignSystemId",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#createsystem",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-createSystem",
    "src/adapters/Adapter.js~Adapter#createSystem",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#deletesystem",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-deleteSystem",
    "src/adapters/Adapter.js~Adapter#deleteSystem",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#getnextid",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-getNextId",
    "src/adapters/Adapter.js~Adapter#getNextId",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#getsystem",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-getSystem",
    "src/adapters/Adapter.js~Adapter#getSystem",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#getsystemid",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-getSystemId",
    "src/adapters/Adapter.js~Adapter#getSystemId",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#preparesystem",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-prepareSystem",
    "src/adapters/Adapter.js~Adapter#prepareSystem",
    "method"
  ],
  [
    "src/adapters/adapter.js~adapter#updatesystem",
    "class/src/adapters/Adapter.js~Adapter.html#instance-method-updateSystem",
    "src/adapters/Adapter.js~Adapter#updateSystem",
    "method"
  ],
  [
    "src/adapters/volatileadapter.js",
    "file/src/adapters/VolatileAdapter.js.html",
    "src/adapters/VolatileAdapter.js",
    "file"
  ],
  [
    "src/adapters/volatileadapter.js~volatileadapter#constructor",
    "class/src/adapters/VolatileAdapter.js~VolatileAdapter.html#instance-constructor-constructor",
    "src/adapters/VolatileAdapter.js~VolatileAdapter#constructor",
    "method"
  ],
  [
    "src/adapters/volatileadapter.js~volatileadapter#createsystem",
    "class/src/adapters/VolatileAdapter.js~VolatileAdapter.html#instance-method-createSystem",
    "src/adapters/VolatileAdapter.js~VolatileAdapter#createSystem",
    "method"
  ],
  [
    "src/adapters/volatileadapter.js~volatileadapter#getsystem",
    "class/src/adapters/VolatileAdapter.js~VolatileAdapter.html#instance-method-getSystem",
    "src/adapters/VolatileAdapter.js~VolatileAdapter#getSystem",
    "method"
  ],
  [
    "src/adapters/volatileadapter.js~volatileadapter#updatesystem",
    "class/src/adapters/VolatileAdapter.js~VolatileAdapter.html#instance-method-updateSystem",
    "src/adapters/VolatileAdapter.js~VolatileAdapter#updateSystem",
    "method"
  ],
  [
    "src/errors/customerror.js",
    "file/src/errors/CustomError.js.html",
    "src/errors/CustomError.js",
    "file"
  ],
  [
    "src/errors/customerror.js~customerror#constructor",
    "class/src/errors/CustomError.js~CustomError.html#instance-constructor-constructor",
    "src/errors/CustomError.js~CustomError#constructor",
    "method"
  ],
  [
    "src/errors/customerror.js~customerror#message",
    "class/src/errors/CustomError.js~CustomError.html#instance-member-message",
    "src/errors/CustomError.js~CustomError#message",
    "member"
  ],
  [
    "src/errors/customerror.js~customerror#name",
    "class/src/errors/CustomError.js~CustomError.html#instance-get-name",
    "src/errors/CustomError.js~CustomError#name",
    "member"
  ],
  [
    "src/errors/customerror.js~customerror#stack",
    "class/src/errors/CustomError.js~CustomError.html#instance-member-stack",
    "src/errors/CustomError.js~CustomError#stack",
    "member"
  ],
  [
    "src/errors/notfounderror.js",
    "file/src/errors/NotFoundError.js.html",
    "src/errors/NotFoundError.js",
    "file"
  ],
  [
    "src/errors/notfounderror.js~notfounderror#constructor",
    "class/src/errors/NotFoundError.js~NotFoundError.html#instance-constructor-constructor",
    "src/errors/NotFoundError.js~NotFoundError#constructor",
    "method"
  ],
  [
    "src/errors/notimplementederror.js",
    "file/src/errors/NotImplementedError.js.html",
    "src/errors/NotImplementedError.js",
    "file"
  ],
  [
    "src/errors/notimplementederror.js~notimplementederror#constructor",
    "class/src/errors/NotImplementedError.js~NotImplementedError.html#instance-constructor-constructor",
    "src/errors/NotImplementedError.js~NotImplementedError#constructor",
    "method"
  ]
]